import "./globals.css";

export const metadata = {
  title: "Jesal's Portfolio",
  description: "Generated by NextJS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
